/**
 * ai-summary service
 */

// const OpenAI = require('openai');

export default ({ strapi }) => ({
    async generateExecutiveSummary(articleContent) {
        // 1. Check if AI is enabled/configured
        const apiKey = process.env.OPENAI_API_KEY;
        if (!apiKey) {
            throw new Error('OpenAI API key not configured');
        }

        // 2. Mock implementation until key is provided
        strapi.log.info('Generating summary for content...');

        // const openai = new OpenAI({ apiKey });
        // const response = ...

        return {
            summary_text: "This is a placeholder summary generated by the AI service structure.",
            tokens_used: 0,
            ai_provider: 'placeholder',
            version: '1.0',
            generated_at: new Date()
        };
    },

    async generateAudioSummary(text) {
        // Implementation for TTS
        return {
            duration_seconds: 0,
            generated_at: new Date()
        };
    }
});
