import {
    IconBook,
    IconHeadphones,
    IconCamera,
    IconDeviceGamepad2,
    IconFeather,
    IconMoodSmile,
    IconArrowLeft,
    IconShare,
    IconFileText,
    IconTargetArrow,
    IconPresentation,
    IconPlayerPlay,
    IconPlayerPause,
    IconHeart,
    IconUser,
    IconSettings,
    IconChevronRight,
    IconBell,
    IconMoon,
    IconLanguage,
    IconCreditCard,
    IconShield,
    IconInfoCircle,
    IconHelp,
    IconLock,
    IconBrandGoogle,
    IconBrandApple,
    IconEye,
    IconEyeOff,
} from '@tabler/icons-react';

export const Icons = {
    book: IconBook,
    podcast: IconHeadphones,
    photos: IconCamera,
    games: IconDeviceGamepad2,
    opinion: IconFeather,
    cartoons: IconMoodSmile,
    back: IconArrowLeft,
    share: IconShare,
    original: IconFileText,
    summary: IconTargetArrow,
    guided: IconPresentation,
    play: IconPlayerPlay,
    pause: IconPlayerPause,
    heart: IconHeart,
    user: IconUser,
    settings: IconSettings,
    chevronRight: IconChevronRight,
    bell: IconBell,
    moon: IconMoon,
    language: IconLanguage,
    subscription: IconCreditCard,
    privacy: IconShield,
    info: IconInfoCircle,
    help: IconHelp,
    lock: IconLock,
    google: IconBrandGoogle,
    apple: IconBrandApple,
    eye: IconEye,
    eyeOff: IconEyeOff,
};
